# Generated by Django 3.1.5 on 2021-02-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20210209_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='editing_expires_on_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
