# Generated by Django 3.1.5 on 2021-02-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20210209_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='review/images')),
            ],
        ),
    ]
