# Generated by Django 3.1.5 on 2021-02-09 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0005_expertusers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExpertUsers',
            new_name='ExpertUser',
        ),
    ]
