# Generated by Django 3.1.5 on 2021-02-09 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_expertprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExpertUser',
        ),
    ]
