# Generated by Django 3.1.5 on 2021-02-10 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_auto_20210210_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='Credits',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
