# Generated by Django 3.1.5 on 2021-02-10 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_expertprofile_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expertprofile',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='expertprofile',
            name='number',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
