# Generated by Django 3.1.5 on 2021-02-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0014_review_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertprofile',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expertprofile',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
